### ISSUE TITLE
Получение списка ресурсов неавторизованным пользователем

### ISSUE THREAD

**Issue by 0nkery** [herald-it/goncord.ex#4]
Сейчас при обращении на `/api/v0/menu/` без указания куков или заголовков возвращается 401 ошибка.

Нужно, чтобы задавалась "роль по умолчанию" для неавторизованных пользователей и список отображался для этой роли.

**Comment by demoj1** [comment]
Лучшая тактика =) Держи issue 2 года и закрывай)

**Comment by 0nkery** [comment]
Я уже не помню, актуально ли это вообще. :)
